# Food Truck Finder API
---
swagger: "2.0"
info:
  title: "Food Truck API"
  description: "Get information about the trucks and events in The Chicago Food Truck Finder"
  version: "1.0.0"
host: "chicagofoodtrucklocator.appspot.com"
schemes:
  - "https"
security: []
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
paths:
  "/services/trucks":
    get:
      parameters:
        - name: active
          in: query
          required: false
          description: If false - return just inactive, if true return just active, if 'all' then return all trucks
          type : string
      description: "Gets all the trucks"
      operationId: trucks
      responses:
        200:
          description: "Success."
          schema:
            type: array
            items:
              $ref: "#/definitions/Truck"
  "/services/v3/trucks/{truckId}":
    get:
      parameters:
        - name: truckId
          in: path
          required: true
          description: The truck ID
          type : string
      description: "Get a truck"
      produces:
        - application/json
      operationId: trucks-beacons
      responses:
        200:
          description: "Success."
          schema:
            $ref: "#/definitions/Truck"
        404:
          description: "If the truck is not found"
definitions:
  Truck:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      url:
        type: string
      categories:
        type: array
        items:
          type: string        
      description:
        type: string
      twitterHandle:
        type: string
      twittalyzer:
        type: boolean
      defaultCity:
        type: string
      instagram:
        type: string
      facebook:
        description: The facebook URI for the foodtruck
        type: string
      inactive:
        type: boolean
      email:
        type: string
      savory:
        type: boolean
      phone:
        type: string
      hidden:
        type: boolean
      previewIcon:
        type: string
      menuUrl:
        type: string
      fleetSize:
        type: integer
      blacklistLocationNames:
        type: array
        items:
          type: string        
      phoneticAliases:
        type: array
        items:
          type: string        
      neverLinkTwitter:
        type: boolean
      postDailySchedule:
        type: boolean
      postWeeklySchedule:
        type: boolean
      postAtNewStop:
        type: boolean
      disableBeaconsUntilLunchtime:
        type: boolean
      notifyWhenLeaving:
        type: boolean
      notifyWhenDeviceIssues:
        type: boolean
