# [START runtime]
runtime: java
vm: true

module: confighub

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

runtime_config:
  jdk: openjdk8
  server: jetty9

manual_scaling:
  instances: 1
# [END runtime]